export const DEPARTMENTS = [
  "Pediatrics",
  "Orthopedics",
  "Cardiology",
  "Neurology",
  "Oncology",
  "Radiology",
  "Physical Therapy",
  "Dermatology",
  "ENT",
];

export const SEEDED_DOCTORS = [
  {
    firstName: "Ayesha",
    lastName: "Khan",
    doctorDepartment: "Pediatrics",
    gender: "Female",
  },
  {
    firstName: "Maira",
    lastName: "Shah",
    doctorDepartment: "Pediatrics",
    gender: "Female",
  },
  {
    firstName: "Bilal",
    lastName: "Riaz",
    doctorDepartment: "Orthopedics",
    gender: "Male",
  },
  {
    firstName: "Farhan",
    lastName: "Siddiqui",
    doctorDepartment: "Orthopedics",
    gender: "Male",
  },
  {
    firstName: "Hina",
    lastName: "Farooq",
    doctorDepartment: "Cardiology",
    gender: "Female",
  },
  {
    firstName: "Rehan",
    lastName: "Iqbal",
    doctorDepartment: "Cardiology",
    gender: "Male",
  },
  {
    firstName: "Usman",
    lastName: "Tariq",
    doctorDepartment: "Neurology",
    gender: "Male",
  },
  {
    firstName: "Komal",
    lastName: "Aslam",
    doctorDepartment: "Neurology",
    gender: "Female",
  },
  {
    firstName: "Sana",
    lastName: "Ali",
    doctorDepartment: "Oncology",
    gender: "Female",
  },
  {
    firstName: "Taimoor",
    lastName: "Qazi",
    doctorDepartment: "Oncology",
    gender: "Male",
  },
  {
    firstName: "Hamza",
    lastName: "Qureshi",
    doctorDepartment: "Radiology",
    gender: "Male",
  },
  {
    firstName: "Noreen",
    lastName: "Fatima",
    doctorDepartment: "Radiology",
    gender: "Female",
  },
  {
    firstName: "Nadia",
    lastName: "Javed",
    doctorDepartment: "Physical Therapy",
    gender: "Female",
  },
  {
    firstName: "Danish",
    lastName: "Malik",
    doctorDepartment: "Physical Therapy",
    gender: "Male",
  },
  {
    firstName: "Areeba",
    lastName: "Iqbal",
    doctorDepartment: "Dermatology",
    gender: "Female",
  },
  {
    firstName: "Mehwish",
    lastName: "Rauf",
    doctorDepartment: "Dermatology",
    gender: "Female",
  },
  {
    firstName: "Sameer",
    lastName: "Nawaz",
    doctorDepartment: "ENT",
    gender: "Male",
  },
  {
    firstName: "Urooj",
    lastName: "Nadeem",
    doctorDepartment: "ENT",
    gender: "Female",
  },
];
